import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "YouGen auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`bg-white fixed left-0 top-0 z-50 w-full h-screen`}
    >
      <div className="px-28 h-[60px] flex justify-start items-center text-3xl">YouGen</div>

      {children}
    </div>
  );
}
