import { NavBar } from "@/components/navbar/navBar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "YouGen auth",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="fixed top-0 left-0 w-full h-screen">
                    <div className="flex w-full">
                        <div className="w-[25%] relative h-[100vh] pb-[65px] bg-gray-90 0 px-4">
                            <NavBar/>
                        </div>
                        <div className="w-[75%] relative h-[100vh] bg-gray-950">
                            {children}
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
